In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_excel("/kaggle/input/and-or-gate-using-perceptron/And_or_gate.xlsx")

In [3]:
df.head(4)

X1  X2  Output
0   0   1       0
1   1   0       0
2   0   0       0
3   1   1       1

In [4]:
x = df.drop(columns='Output').head(4).values
x1 = x = df.drop(columns='Output').tail(4).values

In [5]:
y = df['Output'].head(4).values
y1 = df['Output'].tail(4).values

In [6]:
class MyPerceptron:
    
    def __init__(self, learning_rate=0.1, n_iterations=10000):
        
        self.lr = learning_rate
        self.epochs = n_iterations
        self.weights = None
        self.bias = None
    
    def fit(self, x, y):
        
        self.weights = np.zeros(x.shape[1])
        self.bias = 0
        
        for epoch in range(self.epochs):
            for i in range(x.shape[0]):
                y_pred = np.dot(self.weights, x[i]) + self.bias
                self.weights = self.weights + self.lr * (y[i] - y_pred) * x[i]
                self.bias = self.bias + self.lr * (y[i] - y_pred) * 1
        
        print('Training Complete')
        print(self.weights)
        print(self.bias)
        
    def activation_function(self, activation):
        
        if activation >= 0:
            return 1
        else:
            return 0
    
    def predict(self, x):
        
        y_pred = []
        
        for i in range(x.shape[0]):
            y_pred.append(self.activation_function(np.dot(self.weights, x[i]) + self.bias))
            
        return np.array(y_pred)

In [7]:
clf = MyPerceptron()

# **Fitting AND Gate**

In [8]:
clf.fit(np.array([[0,1],[1,0],[1,1],[0,0]]), np.array([0,0,1,0]))

Training Complete
[0.55555556 0.52777778]
-0.24999999999999925


In [9]:
x_test = df.drop(columns='Output').head(4).values
x_test

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1]])

In [10]:
y_pred = clf.predict(x_test)

In [11]:
y_pred

array([1, 1, 0, 1])

In [12]:
accuracy_score(y_pred, np.array([0,0,0,1])) * 100

50.0

# **Fitting OR Gate**

In [13]:
clf.fit(np.array([[0,0],[1,0],[0,0],[1,1]]), y1)

Training Complete
[-1.38009639e-15 -1.00000000e+00]
1.0000000000000009


In [14]:
x_test1 = df.drop(columns='Output').tail(4).values
x_test1

array([[0, 1],
       [1, 0],
       [1, 1],
       [0, 0]])

In [15]:
y_pred1 = clf.predict(x_test1)

In [16]:
y_pred1

array([1, 1, 1, 1])

In [17]:
accuracy_score(y_pred1, np.array([1,1,1,0])) * 100

75.0

# **Hinge Loss as Perceptron Loss Function and Step Function as the Activation Function**

In [18]:
def perceptron(X,y):
    
    w1=w2=b=1
    lr = 0.1
    
    for j in range(100000):
    
        for i in range(X.shape[0]):

            # check condition
            z = w1*X[i][0] + w2*X[i][1] + b

            if z*y[i] < 0:
                w1 = w1 + lr*y[i]*X[i][0]
                w2 = w2 + lr*y[i]*X[i][1]
                b = b + lr*y[i]
            
    return w1,w2,b

In [19]:
w1,w2,b = perceptron(np.array([[0,0],[0,1],[1,1],[0,0]]), np.array([0,0,1,0]))

In [20]:
val = w1 * 1 + w2 * 1 + b
val

3